# vim:fileencoding=utf-8:foldmethod=marker

# : App {{{

[app]
overall = {}

# : }}}


# : Manager {{{

[mgr]
cwd = { fg = "lightcyan" }

# hovered = { bg = "black" }
# preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#f9e2af", bold = true, italic = true, underline = true }
find_position = { fg = "#f5c2e7", bg = "reset", bold = true, italic = true }

# Marker
marker_copied = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_cut = { fg = "#f38ba8", bg = "#f38ba8" }
marker_marked = { fg = "#94e2d5", bg = "#94e2d5" }
marker_selected = { fg = "#f9e2af", bg = "#f9e2af" }

# Count
count_copied = { fg = "#1e1e2e", bg = "#a6e3a1" }
count_cut = { fg = "#1e1e2e", bg = "#f38ba8" }
count_selected = { fg = "#1e1e2e", bg = "#f9e2af" }

# Border
border_symbol = "│"
border_style = { fg = "black" }

# : }}}


# : Tabs {{{

[tabs]
active = { fg = "#1e1e2e", bg = "#89b4fa", bold = true }
inactive = { fg = "#89b4fa", bg = "#313244" }

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#1e1e2e", bg = "blue", bold = true }
normal_alt = { fg = "blue", bg = "black" }

# Select mode
select_main = { fg = "#1e1e2e", bg = "#94e2d5", bold = true }
select_alt = { fg = "#94e2d5", bg = "#313244" }

# Unset mode
unset_main = { fg = "#1e1e2e", bg = "#f2cdcd", bold = true }
unset_alt = { fg = "#f2cdcd", bg = "#313244" }

# : }}}

# : Indicator of hovered file {{{

[indicator]
parent = { reversed = true, bold = true }
current = { reversed = true, bold = true }
preview = { fg = "white", underline = false }
padding = { open = "█", close = "█" }
# : }}}


# : Status bar {{{

[status]
overall = {}
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep = { fg = "black" }
perm_type = { fg = "#89b4fa" }
perm_read = { fg = "#f9e2af" }
perm_write = { fg = "#f38ba8" }
perm_exec = { fg = "#a6e3a1" }

# Progress
progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#a6e3a1", bg = "#45475a" }
progress_error = { fg = "#f9e2af", bg = "#f38ba8" }

# : }}}


# : Pick {{{

[pick]
border = { fg = "#89b4fa" }
active = { fg = "#f5c2e7", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "#89b4fa" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#89b4fa" }

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#89b4fa" }
title = {}
hovered = { fg = "#f5c2e7", bold = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#313244" }
cand = { fg = "#94e2d5" }
rest = { fg = "#9399b2" }
desc = { fg = "#f5c2e7" }
separator = "  "
separator_style = { fg = "#585b70" }

# : }}}


# : Help {{{

[help]
on = { fg = "#94e2d5" }
run = { fg = "#f5c2e7" }
hovered = { reversed = true, bold = true }
footer = { fg = "#313244", bg = "#cdd6f4" }

# : }}}


# : Spotter {{{

[spot]
border = { fg = "#89b4fa" }
title = { fg = "#89b4fa" }
tbl_col = { fg = "#94e2d5" }
tbl_cell = { fg = "#f5c2e7", bg = "#45475a" }

# : }}}


# : Notification {{{

[notify]
title_info = { fg = "#a6e3a1" }
title_warn = { fg = "#f9e2af" }
title_error = { fg = "#f38ba8" }
icon_info = ""
icon_warn = ""
icon_error = ""

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Image
  { mime = "image/*", fg = "#94e2d5" },
  # Media
  { mime = "{audio,video}/*", fg = "#f9e2af" },
  # Archive
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },
  # Document
  { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },
  # Virtual file system
  { mime = "vfs/{absent,stale}", fg = "#9399b2" },
  # Fallback
  { url = "*", is = "block", fg = "#74c7ec", bg = "#313244" },
  { url = "*", is = "char", fg = "#f5c2e7", bg = "#313244" },
  { url = "*/", fg = "lightblue", bold = true },
  { url = "*", is = "exec", fg = "#a6e3a1", bold = true },
  { url = "*", is = "link", fg = "#89dceb" },
  { url = "*", is = "orphan", fg = "#181825", bg = "#f38ba8", bold = true },
  { url = "*", is = "fifo", fg = "#11111b", bg = "#89b4fa" },
  { url = "*", is = "sock", fg = "#11111b", bg = "#f5c2e7" },
  { url = "*", is = "sticky", fg = "#9399b2" },
  { url = "*.1", fg = "#cdd6f4" },
  { url = "*.a", fg = "#a6e3a1", bold = true },
  { url = "*.c", fg = "#f9e2af", bold = true },
  { url = "*.d", fg = "#f9e2af", bold = true },
  { url = "*.f", fg = "#f9e2af", bold = true },
  { url = "*.h", fg = "#f9e2af", bold = true },
  { url = "*.m", fg = "#f9e2af", bold = true },
  { url = "*.o", fg = "#6c7086" },
  { url = "*.p", fg = "#f9e2af", bold = true },
  { url = "*.r", fg = "#f9e2af", bold = true },
  { url = "*.t", fg = "#f9e2af", bold = true },
  { url = "*.v", fg = "#f9e2af", bold = true },
  { url = "*.z", fg = "#eba0ac", bold = true },
  { url = "*.7z", fg = "#eba0ac", bold = true },
  { url = "*.ai", fg = "#cba6f7", bold = true },
  { url = "*.go", fg = "#f9e2af", bold = true },
  { url = "*.gz", fg = "#eba0ac", bold = true },
  { url = "*.js", fg = "#f9e2af", bold = true },
  { url = "*.rb", fg = "#f9e2af", bold = true },
  { url = "*.rc", fg = "#fab387", bold = true },
  { url = "*.ts", fg = "#f9e2af", bold = true },
  { url = "*.avi", fg = "#cdd6f4", bold = true },
  { url = "*.bak", fg = "#6c7086" },
  { url = "*.bat", fg = "#a6e3a1", bold = true },
  { url = "*.bin", fg = "#eba0ac", bold = true },
  { url = "*.bmp", fg = "#cba6f7", bold = true },
  { url = "*.cjs", fg = "#f9e2af", bold = true },
  { url = "*.com", fg = "#a6e3a1", bold = true },
  { url = "*.cpp", fg = "#f9e2af", bold = true },
  { url = "*.css", fg = "#f9e2af", bold = true },
  { url = "*.csv", fg = "#f38ba8" },
  { url = "*.dat", fg = "#f9e2af" },
  { url = "*.deb", fg = "#eba0ac", bold = true },
  { url = "*.dll", fg = "#a6e3a1", bold = true },
  { url = "*.doc", fg = "#f38ba8" },
  { url = "*.dot", fg = "#f9e2af", bold = true },
  { url = "*.elm", fg = "#f9e2af", bold = true },
  { url = "*.exe", fg = "#a6e3a1", bold = true },
  { url = "*.gif", fg = "#cba6f7", bold = true },
  { url = "*.git", fg = "#6c7086" },
  { url = "*.ico", fg = "#cba6f7", bold = true },
  { url = "*.inc", fg = "#f9e2af", bold = true },
  { url = "*.ini", fg = "#fab387", bold = true },
  { url = "*.iso", fg = "#eba0ac", bold = true },
  { url = "*.jar", fg = "#eba0ac", bold = true },
  { url = "*.jpg", fg = "#cba6f7", bold = true },
  { url = "*.jsx", fg = "#f9e2af", bold = true },
  { url = "*.log", fg = "#6c7086" },
  { url = "*.lua", fg = "#f9e2af", bold = true },
  { url = "*.mov", fg = "#cdd6f4", bold = true },
  { url = "*.mp3", fg = "#f9e2af" },
  { url = "*.mp4", fg = "#cdd6f4", bold = true },
  { url = "*.msi", fg = "#eba0ac", bold = true },
  { url = "*.nim", fg = "#f9e2af", bold = true },
  { url = "*.nix", fg = "#fab387", bold = true },
  { url = "*.org", fg = "#cdd6f4" },
  { url = "*.otf", fg = "#bac2de", bold = true },
  { url = "*.pgm", fg = "#cba6f7", bold = true },
  { url = "*.php", fg = "#f9e2af", bold = true },
  { url = "*.ps1", fg = "#f9e2af", bold = true },
  { url = "*.psd", fg = "#cba6f7", bold = true },
  { url = "*.svg", fg = "#cba6f7", bold = true },
  { url = "*.tar", fg = "#eba0ac", bold = true },
  { url = "*.tmp", fg = "#6c7086" },
  { url = "*.tsx", fg = "#f9e2af", bold = true },
  { url = "*.ttf", fg = "#bac2de", bold = true },
  { url = "*.txt", fg = "#cdd6f4" },
  { url = "*.vhd", fg = "#eba0ac", bold = true },
  { url = "*.vim", fg = "#f9e2af", bold = true },
  { url = "*.wav", fg = "#f9e2af" },
  { url = "*.yml", fg = "#fab387", bold = true },
  { url = "*.zig", fg = "#f9e2af", bold = true },
  { url = "*.zip", fg = "#eba0ac", bold = true },
  { url = "*.zsh", fg = "#f9e2af", bold = true },
  { url = "*.bash", fg = "#f9e2af", bold = true },
  { url = "*.cljs", fg = "#f9e2af", bold = true },
  { url = "*.conf", fg = "#fab387", bold = true },
  { url = "*.dart", fg = "#f9e2af", bold = true },
  { url = "*.data", fg = "#cba6f7", bold = true },
  { url = "*.diff", fg = "#f9e2af", bold = true },
  { url = "*.docx", fg = "#f38ba8" },
  { url = "*.dump", fg = "#6c7086" },
  { url = "*.fish", fg = "#f9e2af", bold = true },
  { url = "*.html", fg = "#cdd6f4" },
  { url = "*.info", fg = "#cdd6f4" },
  { url = "*.java", fg = "#f9e2af", bold = true },
  { url = "*.jpeg", fg = "#cba6f7", bold = true },
  { url = "*.json", fg = "#fab387", bold = true },
  { url = "*.lisp", fg = "#f9e2af", bold = true },
  { url = "*.lock", fg = "#6c7086" },
  { url = "*.make", fg = "#74c7ec", bold = true },
  { url = "*.mpeg", fg = "#cdd6f4", bold = true },
  { url = "*.nims", fg = "#f9e2af", bold = true },
  { url = "*.odin", fg = "#f9e2af", bold = true },
  { url = "*.psd1", fg = "#f9e2af", bold = true },
  { url = "*.psm1", fg = "#f9e2af", bold = true },
  { url = "*.sass", fg = "#f9e2af", bold = true },
  { url = "*.scss", fg = "#f9e2af", bold = true },
  { url = "*.swap", fg = "#fab387", bold = true },
  { url = "*.toml", fg = "#fab387", bold = true },
  { url = "*.webm", fg = "#cdd6f4", bold = true },
  { url = "*.webp", fg = "#cba6f7", bold = true },
  { url = "*.woff", fg = "#bac2de", bold = true },
  { url = "*.yaml", fg = "#fab387", bold = true },
  { url = "*fstab", fg = "#fab387", bold = true },
  { url = "*group", fg = "#fab387", bold = true },
  { url = "*hosts", fg = "#fab387", bold = true },
  { url = "*stdin", fg = "#6c7086" },
  { url = "*v.mod", fg = "#74c7ec", bold = true },
  { url = "*.aria2", fg = "#6c7086" },
  { url = "*.bazel", fg = "#74c7ec", bold = true },
  { url = "*.blend", fg = "#cba6f7" },
  { url = "*.cabal", fg = "#f9e2af", bold = true },
  { url = "*.cache", fg = "#6c7086" },
  { url = "*.class", fg = "#6c7086" },
  { url = "*.cmake", fg = "#74c7ec", bold = true },
  { url = "*.ctags", fg = "#6c7086" },
  { url = "*.dylib", fg = "#a6e3a1", bold = true },
  { url = "*.dyn_o", fg = "#6c7086" },
  { url = "*.gcode", fg = "#f9e2af", bold = true },
  { url = "*.ipynb", fg = "#f9e2af", bold = true },
  { url = "*.jhtml", fg = "#cdd6f4" },
  { url = "*.lagda", fg = "#f9e2af", bold = true },
  { url = "*.mdown", fg = "#cdd6f4" },
  { url = "*.mhtml", fg = "#eba0ac", bold = true },
  { url = "*.mount", fg = "#fab387", bold = true },
  { url = "*.pages", fg = "#f38ba8" },
  { url = "*.paq8n", fg = "#eba0ac", bold = true },
  { url = "*.paq8o", fg = "#eba0ac", bold = true },
  { url = "*.patch", fg = "#f9e2af", bold = true },
  { url = "*.plist", fg = "#6c7086" },
  { url = "*.pptsm", fg = "#f38ba8" },
  { url = "*.pptxm", fg = "#f38ba8" },
  { url = "*.rmeta", fg = "#6c7086" },
  { url = "*.scala", fg = "#f9e2af", bold = true },
  { url = "*.shtml", fg = "#cdd6f4" },
  { url = "*.state", fg = "#6c7086" },
  { url = "*.swift", fg = "#f9e2af", bold = true },
  { url = "*.timer", fg = "#fab387", bold = true },
  { url = "*.toast", fg = "#eba0ac", bold = true },
  { url = "*.vcard", fg = "#f38ba8" },
  { url = "*.woff2", fg = "#bac2de", bold = true },
  { url = "*.xhtml", fg = "#cdd6f4" },
  { url = "*LEGACY", fg = "#b4befe", bold = true },
  { url = "*NOTICE", fg = "#b4befe", bold = true },
  { url = "*README", fg = "#b4befe", bold = true },
  { url = "*go.mod", fg = "#74c7ec", bold = true },
  { url = "*go.sum", fg = "#6c7086" },
  { url = "*mounts", fg = "#fab387", bold = true },
  { url = "*passwd", fg = "#fab387", bold = true },
  { url = "*shadow", fg = "#fab387", bold = true },
  { url = "*stderr", fg = "#6c7086" },
  { url = "*stdout", fg = "#6c7086" },
  { url = "*.bashrc", fg = "#f9e2af", bold = true },
  { url = "*.config", fg = "#fab387", bold = true },
  { url = "*.device", fg = "#fab387", bold = true },
  { url = "*.dyn_hi", fg = "#6c7086" },
  { url = "*.flake8", fg = "#74c7ec", bold = true },
  { url = "*.github", fg = "#6c7086" },
  { url = "*.gradle", fg = "#f9e2af", bold = true },
  { url = "*.groovy", fg = "#f9e2af", bold = true },
  { url = "*.ignore", fg = "#74c7ec", bold = true },
  { url = "*.matlab", fg = "#f9e2af", bold = true },
  { url = "*.nimble", fg = "#f9e2af", bold = true },
  { url = "*.sample", fg = "#cdd6f4", bold = true },
  { url = "*.socket", fg = "#fab387", bold = true },
  { url = "*.target", fg = "#fab387", bold = true },
  { url = "*.tfvars", fg = "#f9e2af", bold = true },
  { url = "*AUTHORS", fg = "#b4befe", bold = true },
  { url = "*CHANGES", fg = "#b4befe", bold = true },
  { url = "*COPYING", fg = "#7f849c" },
  { url = "*HISTORY", fg = "#b4befe", bold = true },
  { url = "*INSTALL", fg = "#b4befe", bold = true },
  { url = "*LICENCE", fg = "#7f849c" },
  { url = "*LICENSE", fg = "#7f849c" },
  { url = "*PATENTS", fg = "#7f849c" },
  { url = "*TODO.md", fg = "#f5c2e7", bold = true },
  { url = "*VERSION", fg = "#b4befe", bold = true },
  { url = "*crontab", fg = "#fab387", bold = true },
  { url = "*uv.lock", fg = "#6c7086" },
  { url = "*.alembic", fg = "#cba6f7" },
  { url = "*.desktop", fg = "#fab387", bold = true },
  { url = "*.gemspec", fg = "#74c7ec", bold = true },
  { url = "*.mailmap", fg = "#74c7ec", bold = true },
  { url = "*.numbers", fg = "#f38ba8" },
  { url = "*.profile", fg = "#f9e2af", bold = true },
  { url = "*.service", fg = "#fab387", bold = true },
  { url = "*.textile", fg = "#cdd6f4" },
  { url = "*.tfstate", fg = "#6c7086" },
  { url = "*Doxyfile", fg = "#74c7ec", bold = true },
  { url = "*Makefile", fg = "#74c7ec", bold = true },
  { url = "*TODO.txt", fg = "#f5c2e7", bold = true },
  { url = "*crypttab", fg = "#fab387", bold = true },
  { url = "*grub.cfg", fg = "#fab387", bold = true },
  { url = "*hostname", fg = "#fab387", bold = true },
  { url = "*networks", fg = "#fab387", bold = true },
  { url = "*setup.py", fg = "#74c7ec", bold = true },
  { url = "*.DS_Store", fg = "#6c7086" },
  { url = "*.asciidoc", fg = "#cdd6f4" },
  { url = "*.aseprite", fg = "#cba6f7", bold = true },
  { url = "*.cmake.in", fg = "#74c7ec", bold = true },
  { url = "*.fdignore", fg = "#74c7ec", bold = true },
  { url = "*.kdevelop", fg = "#74c7ec", bold = true },
  { url = "*.lockfile", fg = "#6c7086" },
  { url = "*.markdown", fg = "#cdd6f4" },
  { url = "*.rgignore", fg = "#74c7ec", bold = true },
  { url = "*.snapshot", fg = "#fab387", bold = true },
  { url = "*.tfignore", fg = "#74c7ec", bold = true },
  { url = "*CHANGELOG", fg = "#b4befe", bold = true },
  { url = "*COPYRIGHT", fg = "#7f849c" },
  { url = "*README.md", fg = "#b4befe", bold = true },
  { url = "*bun.lockb", fg = "#6c7086" },
  { url = "*configure", fg = "#74c7ec", bold = true },
  { url = "*securetty", fg = "#fab387", bold = true },
  { url = "*.automount", fg = "#fab387", bold = true },
  { url = "*.gitconfig", fg = "#74c7ec", bold = true },
  { url = "*.gitignore", fg = "#74c7ec", bold = true },
  { url = "*.localized", fg = "#6c7086" },
  { url = "*.scons_opt", fg = "#6c7086" },
  { url = "*.terraform", fg = "#f9e2af", bold = true },
  { url = "*.timestamp", fg = "#6c7086" },
  { url = "*CHANGES.md", fg = "#b4befe", bold = true },
  { url = "*CODEOWNERS", fg = "#74c7ec", bold = true },
  { url = "*Dockerfile", fg = "#89dceb" },
  { url = "*INSTALL.md", fg = "#b4befe", bold = true },
  { url = "*README.txt", fg = "#b4befe", bold = true },
  { url = "*SConscript", fg = "#74c7ec", bold = true },
  { url = "*SConstruct", fg = "#74c7ec", bold = true },
  { url = "*.cirrus.yml", fg = "#74c7ec" },
  { url = "*.gitmodules", fg = "#74c7ec", bold = true },
  { url = "*.synctex.gz", fg = "#6c7086" },
  { url = "*.travis.yml", fg = "#74c7ec" },
  { url = "*CHANGES.txt", fg = "#b4befe", bold = true },
  { url = "*INSTALL.txt", fg = "#b4befe", bold = true },
  { url = "*LICENSE-MIT", fg = "#7f849c" },
  { url = "*MANIFEST.in", fg = "#74c7ec", bold = true },
  { url = "*Makefile.am", fg = "#74c7ec", bold = true },
  { url = "*Makefile.in", fg = "#6c7086" },
  { url = "*known_hosts", fg = "#fab387", bold = true },
  { url = "*poetry.lock", fg = "#6c7086" },
  { url = "*.applescript", fg = "#f9e2af", bold = true },
  { url = "*.fdb_latexmk", fg = "#6c7086" },
  { url = "*.sparseimage", fg = "#eba0ac", bold = true },
  { url = "*.webmanifest", fg = "#fab387", bold = true },
  { url = "*CHANGELOG.md", fg = "#b4befe", bold = true },
  { url = "*CONTRIBUTING", fg = "#b4befe", bold = true },
  { url = "*CONTRIBUTORS", fg = "#b4befe", bold = true },
  { url = "*appveyor.yml", fg = "#74c7ec" },
  { url = "*configure.ac", fg = "#74c7ec", bold = true },
  { url = "*.bash_profile", fg = "#f9e2af", bold = true },
  { url = "*.clang-format", fg = "#74c7ec", bold = true },
  { url = "*.dockerignore", fg = "#74c7ec", bold = true },
  { url = "*.editorconfig", fg = "#74c7ec", bold = true },
  { url = "*CHANGELOG.txt", fg = "#b4befe", bold = true },
  { url = "*Containerfile", fg = "#89dceb" },
  { url = "*.aseprite-keys", fg = "#cdd6f4" },
  { url = "*.gitattributes", fg = "#74c7ec", bold = true },
  { url = "*.gitlab-ci.yml", fg = "#74c7ec" },
  { url = "*CMakeCache.txt", fg = "#6c7086" },
  { url = "*CMakeLists.txt", fg = "#74c7ec", bold = true },
  { url = "*LICENSE-APACHE", fg = "#7f849c" },
  { url = "*pyproject.toml", fg = "#74c7ec", bold = true },
  { url = "*CODE_OF_CONDUCT", fg = "#b4befe", bold = true },
  { url = "*CONTRIBUTING.md", fg = "#b4befe", bold = true },
  { url = "*CONTRIBUTORS.md", fg = "#b4befe", bold = true },
  { url = "*authorized_keys", fg = "#fab387", bold = true },
  { url = "*.containerignore", fg = "#74c7ec", bold = true },
  { url = "*.sconsign.dblite", fg = "#6c7086" },
  { url = "*CONTRIBUTING.txt", fg = "#b4befe", bold = true },
  { url = "*CONTRIBUTORS.txt", fg = "#b4befe", bold = true },
  { url = "*requirements.txt", fg = "#74c7ec", bold = true },
  { url = "*.aseprite-brushes", fg = "#cdd6f4" },
  { url = "*package-lock.json", fg = "#6c7086" },
  { url = "*CODE_OF_CONDUCT.md", fg = "#b4befe", bold = true },
  { url = "*.CFUserTextEncoding", fg = "#6c7086" },
  { url = "*.aseprite-extension", fg = "#eba0ac", bold = true },
  { url = "*CODE_OF_CONDUCT.txt", fg = "#b4befe", bold = true },
  { url = "*azure-pipelines.yml", fg = "#74c7ec" },
]

# : }}}

[icon]
prepend_conds = [{ if = "link & dir", text = "", fg = "#74c7ec" }]
dirs = [
  { name = ".config", text = "", fg = "#f5c2e7" },
  { name = "dots", text = "", fg = "#f5c2e7" },
  { name = ".git", text = "󰊢", fg = "#6c7086" },
  { name = ".github", text = "", fg = "#6c7086" },
  { name = ".npm", text = "", fg = "#6c7086" },
  { name = "Desktop", text = "", fg = "#94e2d5" },
  { name = "Development", text = "", fg = "#94e2d5" },
  { name = "Documents", text = "󱔘", fg = "#94e2d5" },
  { name = "Downloads", text = "󰉍", fg = "#94e2d5" },
  { name = "Library", text = "", fg = "#94e2d5" },
  { name = "Movies", text = "", fg = "#94e2d5" },
  { name = "Music", text = "", fg = "#94e2d5" },
  { name = "Pictures", text = "", fg = "#94e2d5" },
  { name = "Public", text = "", fg = "#94e2d5" },
  { name = "Videos", text = "", fg = "#94e2d5" },
]
conds = [
  # Special files
  { if = "orphan", text = "", fg = "#cdd6f4" },
  { if = "link", text = "", fg = "#89dceb" },
  { if = "block", text = "", fg = "#f2cdcd" },
  { if = "char", text = "", fg = "#f2cdcd" },
  { if = "fifo", text = "", fg = "#f2cdcd" },
  { if = "sock", text = "", fg = "#f2cdcd" },
  { if = "sticky", text = "", fg = "#f2cdcd" },
  { if = "dummy", text = "", fg = "#f38ba8" },

  # Fallback
  { if = "dir & hovered", text = "", fg = "lightblue" },
  { if = "hidden & dir", text = "", fg = "blue" },
  { if = "dir", text = "", fg = "lightblue" },
  { if = "exec", text = "", fg = "lightgreen" },
  { if = "!dir", text = "", fg = "#cdd6f4" },
]
